app-text/stardict: fix missing gmodule error
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.1/../../../../x86_64-pc-linux-gnu/bin/ld:
lib/.libs/libstardict.a(pluginmanager.o): undefined reference to symbol
'g_module_symbol'
/usr/lib/gcc/x86_64-pc-linux-gnu/4.8.1/../../../../x86_64-pc-linux-gnu/bin/ld:
note: 'g_module_symbol' is defined in DSO /usr/lib64/libgmodule-2.0.so.0
so try adding it to the linker command line
/usr/lib64/libgmodule-2.0.so.0: could not read symbols: Invalid
operation
collect2: error: ld returned 1 exit status
make[4]: *** [stardict] Error 1

Signed-off-by: Lan Yixun (dlan) <dennis.yxun@gmail.com>