dev-android/fastboot: fix missing ext4_crc16 error
abel.o label_android_property.o label_file.o -lz
ext4_utils.o: In function `ext4_update_free':
ext4_utils.c:(.text+0xd35): undefined reference to `ext4_crc16'
ext4_utils.c:(.text+0xd47): undefined reference to `ext4_crc16'
ext4_utils.c:(.text+0xd63): undefined reference to `ext4_crc16'

Signed-off-by: Lan Yixun (dlan) <dennis.yxun@gmail.com>