net-proxy/clash-rs: add 0.9.1, drop 0.9.0
compile bindgen 0.72.1 need libclang.so:

thread 'main' panicked at /var/tmp/portage/net-proxy/clash-rs-0.9.1/work/cargo_home/gentoo/bindgen-0.72.1/lib.rs:616:27: Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"

Closes: https://github.com/microcai/gentoo-zh/issues/8155
Signed-off-by: jinqiang zhang <peeweep@0x0.ee>